---
driver:
  name: vagrant
  network:
    # Allow access to kimchi console
    - [forwarded_port, {guest: 8001, host: 8001, auto_correct: false}]

provisioner:
  name: chef_zero

platforms:
  - name: centos-6.6

suites:
  - name: default
    run_list:
      - recipe[kimchi::default]
    attributes:
